# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c11f30ccf42b0d250f7063be305484b46618c08915d02f7bf8aa7c13875d7a07790012fe367e7f36d33c2d2e9ecd5d6195af0ecf30dd944a5744fee22399299

test:
  secret_key_base: b6985ad67f47283db494747c4efcfc1d8bfd6ca2170a13a5597fdac9e0910a917a94c68303a639f2d04f18e05bc7552a926017f1f51df0a61215abe66e29c52f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
